name: Crates CI

on:
  push:
    branches:
      - main
    paths:
      - ".github/**"
      - "crates/**"

  pull_request:
    branches:
      - main
    paths:
      - ".github/**"
      - "crates/**"

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - run: echo "executing!"
