name: Packages CI

on:
  push:
    branches:
      - "main"
    paths:
      - ".github/**"
      - "package.json"
      - "packages/**"

  pull_request:
    branches:
      - "main"
    paths:
      - ".github/**"
      - "package.json"
      - "packages/github/**"

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - run: echo "executing!"
