name: Root CI

on:
  push:
    branches:
      - "main"
    paths:
      - ".github/**"
      - "*"

  pull_request:
    branches:
      - "main"
    paths:
      - ".github/**"
      - "*"

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - run: echo "executing!"
